version: "3.8"

services:
  openwa:
    build:
      context: .
      dockerfile: Dockerfile
    image: openwa:latest
    env_file:
      - .env
    ports:
      - "55111:55111"
    environment:
      HOST: "${HOST}"
      FE_PORT: "${FE_PORT}"
      BE_PORT: "${BE_PORT}"
      OPENWA_AUTO_OPEN: "${OPENWA_AUTO_OPEN}"
      OPENWA_USE_WWEBJS: "${OPENWA_USE_WWEBJS}"
      OPENWA_ALLOW_MOCK: "${OPENWA_ALLOW_MOCK}"
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - dokploy-network
    volumes:
      - openwa-storage:/app/storage
    restart: unless-stopped

networks:
  dokploy-network:
    external: true

volumes:
  openwa-storage:
